engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - app/**
  - lib/**
  - "**.rb"
  - "**.erb"
  - "**.js"
  - "**.css"

exclude_paths:
- db/
- spec/
- test/
- vendor/
