sudo: required 

before_install:  
 - sudo apt-get install unzip
 - wget -N http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip -P ~/Downloads
 - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
 - chmod +x ~/Downloads/chromedriver
 - sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
 - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
 - gem install selenium-webdriver
 - - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - bundle exec rails db:create db:migrate

addons:
  apt:
    sources:
    - google-chrome
  packages:
    - google-chrome-stable
cache: bundler
language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec rspec
  - bundle exec cucumber --profile default

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
dist: xenial

