before_script:
  - bundle exec rails db:create db:migrate
  - gem install codeclimate-test-reporter

cache: bundler

language: ruby

rvm:
  - 2.3.1

script:
  - bundle exec rspec

after_success:
  - CODECLIMATE_REPO_TOKEN=eeaa06a888388e77f5137dde75ddb580696f32796ce7eb75f065ea53930df966 bundle exec codeclimate-test-reporter 

sudo: false

dist: xenial
